/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sumptus.view;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JDialog;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import sumptus.dao.AreaDAO;
import sumptus.dao.DataBase;
import sumptus.model.Area;

/**
 *
 * @author jessicadagostini
 */
public class AreaFrame extends javax.swing.JFrame {

    private AreaDAO areaDAO;
    private List<Area> areas;
    private AreaTableModel areaTbModel;
    private Area area;

    /**
     * Creates new form AreaFrame
     */
    public AreaFrame() {
        initComponents();
        findAreas();
    }

    public void findAreas() {
        try {
            areaDAO = new AreaDAO(DataBase.connection());
            areas = areaDAO.findAll();
            areaTbModel = new AreaTableModel(areas);
            areasTable.setModel(areaTbModel);
        } catch (SQLException ex) {
            Logger.getLogger(AreaFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editAreaDialog = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        editIdArea = new javax.swing.JTextField();
        editNameArea = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        saveAreaButton = new javax.swing.JButton();
        cancelAreaButton = new javax.swing.JButton();
        areaScrollPane = new javax.swing.JScrollPane();
        areasTable = new javax.swing.JTable();
        areaMenuBar = new javax.swing.JMenuBar();
        newAreaMenu = new javax.swing.JMenu();
        editAreaMenu = new javax.swing.JMenu();
        deleteAreaMenu = new javax.swing.JMenu();

        editAreaDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        editAreaDialog.setTitle("Editar Área");
        editAreaDialog.setMinimumSize(new java.awt.Dimension(400, 300));

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 300));

        jLabel1.setText("ID");

        editIdArea.setEnabled(false);
        editIdArea.setFocusable(false);

        jLabel2.setText("Área");

        saveAreaButton.setText("Salvar");
        saveAreaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAreaButtonActionPerformed(evt);
            }
        });

        cancelAreaButton.setText("Cancelar");
        cancelAreaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAreaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cancelAreaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveAreaButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editNameArea, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editIdArea, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(editIdArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editNameArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveAreaButton)
                    .addComponent(cancelAreaButton))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout editAreaDialogLayout = new javax.swing.GroupLayout(editAreaDialog.getContentPane());
        editAreaDialog.getContentPane().setLayout(editAreaDialogLayout);
        editAreaDialogLayout.setHorizontalGroup(
            editAreaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editAreaDialogLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        editAreaDialogLayout.setVerticalGroup(
            editAreaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sumptus - Áreas");
        setMaximumSize(new java.awt.Dimension(800, 700));
        setMinimumSize(new java.awt.Dimension(800, 700));
        setPreferredSize(new java.awt.Dimension(800, 700));
        setResizable(false);

        areasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        areasTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                areasTableMouseClicked(evt);
            }
        });
        areaScrollPane.setViewportView(areasTable);

        newAreaMenu.setText("Adicionar");
        newAreaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newAreaMenuMouseClicked(evt);
            }
        });
        areaMenuBar.add(newAreaMenu);

        editAreaMenu.setText("Editar");
        editAreaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editAreaMenuMouseClicked(evt);
            }
        });
        areaMenuBar.add(editAreaMenu);

        deleteAreaMenu.setText("Deletar");
        deleteAreaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteAreaMenuMouseClicked(evt);
            }
        });
        areaMenuBar.add(deleteAreaMenu);

        setJMenuBar(areaMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void areasTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_areasTableMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){
            editArea();
        } 
    }//GEN-LAST:event_areasTableMouseClicked

    private void deleteAreaMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteAreaMenuMouseClicked
        // TODO add your handling code here:
        deleteArea();
    }//GEN-LAST:event_deleteAreaMenuMouseClicked

    private void newAreaMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newAreaMenuMouseClicked
        String newArea = JOptionPane.showInputDialog(areaScrollPane,"Digite a nova área", "Sumptus - Nova Área", JOptionPane.INFORMATION_MESSAGE);
        if(newArea != null){
            if (!newArea.trim().isEmpty()) {
                try {
                    AreaDAO DAO = new AreaDAO(DataBase.connection());
                    Area area = new Area();
                    area.setName(newArea);
                    DAO.create(area);
                    JOptionPane.showMessageDialog(null, "Gravado com Sucesso", "Sumptus - Informação", JOptionPane.INFORMATION_MESSAGE);
                    findAreas();
                } catch (SQLException ex) {
                    Logger.getLogger(AreaFrame.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Erro ao gravar área", "Sumptus - Erro", JOptionPane.ERROR);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Por favor, preencha este campo", "Sumptus - Erro", JOptionPane.ERROR_MESSAGE);
                newAreaMenuMouseClicked(evt);
            }
        }
    }//GEN-LAST:event_newAreaMenuMouseClicked

    private void editAreaMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editAreaMenuMouseClicked
        // TODO add your handling code here:
        editArea();
    }//GEN-LAST:event_editAreaMenuMouseClicked

    private void saveAreaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAreaButtonActionPerformed
        // TODO add your handling code here:
        area.setId(Integer.parseInt(editIdArea.getText()));
        area.setName(editNameArea.getText());
        try {
            areaDAO.update(area);
            editAreaDialog.setVisible(false);
            findAreas();
        } catch (SQLException ex) {
            Logger.getLogger(AreaFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveAreaButtonActionPerformed

    private void cancelAreaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAreaButtonActionPerformed
        // TODO add your handling code here:
        editAreaDialog.dispose();
    }//GEN-LAST:event_cancelAreaButtonActionPerformed
    
    private void editArea(){
        Integer areaSelec = areasTable.getSelectedRow();        
        if(areaSelec == -1){
            JOptionPane.showMessageDialog(null, "Por favor, selecione uma área", "Sumptus - Erro", JOptionPane.ERROR_MESSAGE);
        }else {
            area = areas.get(areaSelec);
            editIdArea.setText(area.getId().toString());
            editNameArea.setText(area.getName());            
            editAreaDialog.setVisible(true);
        }
    }
    
    private void deleteArea() {
        Integer areaSelec = areasTable.getSelectedRow();        
        if(areaSelec == -1){
            JOptionPane.showMessageDialog(null, "Por favor, selecione uma área", "Sumptus - Erro", JOptionPane.ERROR_MESSAGE);
        }else {
            area = areas.get(areaSelec);
            int delete = JOptionPane.showConfirmDialog(rootPane, "Deletar \"" + area.getName() + "\"?", "Sumptus - Confirmação", JOptionPane.YES_NO_OPTION);
            System.out.println("Delete = " + delete);
            if (delete == 0) {
                try {
                    String saida = areaDAO.delete(area.getId());
                    JOptionPane.showMessageDialog(rootPane, saida);
                    findAreas();
                } catch (Exception ex) {
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AreaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AreaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AreaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AreaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AreaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar areaMenuBar;
    private javax.swing.JScrollPane areaScrollPane;
    private javax.swing.JTable areasTable;
    private javax.swing.JButton cancelAreaButton;
    private javax.swing.JMenu deleteAreaMenu;
    private javax.swing.JDialog editAreaDialog;
    private javax.swing.JMenu editAreaMenu;
    private javax.swing.JTextField editIdArea;
    private javax.swing.JTextField editNameArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu newAreaMenu;
    private javax.swing.JButton saveAreaButton;
    // End of variables declaration//GEN-END:variables
}
