package sumptus.view;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sumptus.dao.DataBase;
import sumptus.dao.PayFormDAO;
import sumptus.model.PayForm;
import sumptus.model.User;

/**
 *
 * @author Jessica Dagostini
 */
public class PayFormFrame extends javax.swing.JFrame {

    private PayFormDAO pformDAO;
    private List<PayForm> pforms;
    private PayFormTableModel pformTbModel;
    private PayForm pform;
    private User userLogged;

    /**
     * Creates new form PayFormFrame
     */
    public PayFormFrame() {
        initComponents();
        findPforms();
    }

    public PayFormFrame(User userLogged) {
        initComponents();
        findPforms();
        this.userLogged = userLogged;
    }

    public void findPforms() {
        try {
            pformDAO = new PayFormDAO(DataBase.connection());
            pforms = pformDAO.findAll();
            pformTbModel = new PayFormTableModel(pforms);
            pformsTable.setModel(pformTbModel);
        } catch (SQLException ex) {
            Logger.getLogger(PayFormFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editPformDialog = new javax.swing.JDialog();
        editIdPform = new javax.swing.JTextField();
        idLabel = new javax.swing.JLabel();
        editNamePform = new javax.swing.JTextField();
        formLabel = new javax.swing.JLabel();
        cancelPformButton = new javax.swing.JButton();
        savePformButton = new javax.swing.JButton();
        pformScrollPane = new javax.swing.JScrollPane();
        pformsTable = new javax.swing.JTable();
        pformMenuBar = new javax.swing.JMenuBar();
        newPformMenu = new javax.swing.JMenu();
        editPformMenu = new javax.swing.JMenu();
        deletePformMenu = new javax.swing.JMenu();

        editPformDialog.setMinimumSize(new java.awt.Dimension(400, 300));

        editIdPform.setEditable(false);
        editIdPform.setEnabled(false);
        editIdPform.setFocusable(false);

        idLabel.setText("Id");

        formLabel.setText("Forma");

        cancelPformButton.setText("Cancelar");
        cancelPformButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelPformButtonActionPerformed(evt);
            }
        });

        savePformButton.setText("Salvar");
        savePformButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePformButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editPformDialogLayout = new javax.swing.GroupLayout(editPformDialog.getContentPane());
        editPformDialog.getContentPane().setLayout(editPformDialogLayout);
        editPformDialogLayout.setHorizontalGroup(
            editPformDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPformDialogLayout.createSequentialGroup()
                .addGroup(editPformDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(editPformDialogLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelPformButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(savePformButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, editPformDialogLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(editPformDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(formLabel)
                            .addComponent(idLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(editPformDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editIdPform, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editNamePform, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        editPformDialogLayout.setVerticalGroup(
            editPformDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPformDialogLayout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addGroup(editPformDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editIdPform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLabel))
                .addGap(14, 14, 14)
                .addGroup(editPformDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formLabel)
                    .addComponent(editNamePform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editPformDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelPformButton)
                    .addComponent(savePformButton))
                .addGap(83, 83, 83))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sumptus - Formas de Pagamento");
        setMaximumSize(new java.awt.Dimension(800, 700));
        setPreferredSize(new java.awt.Dimension(800, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 700));

        pformsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        pformsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pformsTableMouseClicked(evt);
            }
        });
        pformScrollPane.setViewportView(pformsTable);

        newPformMenu.setText("Adicionar");
        newPformMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newPformMenuMouseClicked(evt);
            }
        });
        pformMenuBar.add(newPformMenu);

        editPformMenu.setText("Editar");
        editPformMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editPformMenuMouseClicked(evt);
            }
        });
        pformMenuBar.add(editPformMenu);

        deletePformMenu.setText("Deletar");
        deletePformMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletePformMenuMouseClicked(evt);
            }
        });
        pformMenuBar.add(deletePformMenu);

        setJMenuBar(pformMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pformScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pformScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pformsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pformsTableMouseClicked
        if (evt.getClickCount() == 2 && userLogged.getAdmin() == true) {
            editPform();
        }
    }//GEN-LAST:event_pformsTableMouseClicked

    private void newPformMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newPformMenuMouseClicked
        if (userLogged.getAdmin() == true) {
            String newPform = JOptionPane.showInputDialog(pformScrollPane, "Digite a nova forma", "Sumptus - Nova Forma Pagamento", JOptionPane.INFORMATION_MESSAGE);
            if (newPform != null) {
                if (!newPform.trim().isEmpty()) {
                    try {
                        PayForm pform = new PayForm();
                        pform.setForm(newPform);
                        String saida = pformDAO.create(pform);
                        JOptionPane.showMessageDialog(null, saida, "Sumptus - Informação", JOptionPane.INFORMATION_MESSAGE);
                        findPforms();
                    } catch (SQLException ex) {
                        Logger.getLogger(AreaFrame.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showMessageDialog(null, "Erro ao gravar pessoa", "Sumptus - Erro", JOptionPane.ERROR);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Por favor, preencha este campo", "Sumptus - Erro", JOptionPane.ERROR_MESSAGE);
                    newPformMenuMouseClicked(evt);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Desculpe, você não tem permissão para fazer isso.", "Sumptus - Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_newPformMenuMouseClicked

    private void cancelPformButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelPformButtonActionPerformed
        editPformDialog.dispose();
    }//GEN-LAST:event_cancelPformButtonActionPerformed

    private void savePformButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePformButtonActionPerformed
        pform.setId(Integer.parseInt(editIdPform.getText()));
        pform.setForm(editNamePform.getText());
        try {
            pformDAO.update(pform);
            editPformDialog.setVisible(false);
            findPforms();
        } catch (SQLException ex) {
            Logger.getLogger(AreaFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_savePformButtonActionPerformed

    private void editPformMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editPformMenuMouseClicked
        if(userLogged.getAdmin() == true) {
            editPform();
        } else {
            JOptionPane.showMessageDialog(null, "Desculpe, você não tem permissão para fazer isso.", "Sumptus - Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editPformMenuMouseClicked

    private void deletePformMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletePformMenuMouseClicked
        if(userLogged.getAdmin() == true) {
            deletePform();
        } else {
            JOptionPane.showMessageDialog(null, "Desculpe, você não tem permissão para fazer isso.", "Sumptus - Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deletePformMenuMouseClicked

    private void editPform() {
        Integer areaSelec = pformsTable.getSelectedRow();
        if (areaSelec == -1) {
            JOptionPane.showMessageDialog(null, "Por favor, selecione uma forma de pagamento", "Sumptus - Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            pform = pforms.get(areaSelec);
            editIdPform.setText(pform.getId().toString());
            editNamePform.setText(pform.getForm());
            editPformDialog.setVisible(true);
        }
    }

    private void deletePform() {
        Integer pformSelec = pformsTable.getSelectedRow();
        if (pformSelec == -1) {
            JOptionPane.showMessageDialog(null, "Por favor, selecione uma forma de pagamento", "Sumptus - Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            pform = pforms.get(pformSelec);
            int delete = JOptionPane.showConfirmDialog(rootPane, "Deletar \"" + pform.getForm() + "\"?", "Sumptus - Confirmação", JOptionPane.YES_NO_OPTION);
            System.out.println("Delete = " + delete);
            if (delete == 0) {
                try {
                    String saida = pformDAO.delete(pform.getId());
                    JOptionPane.showMessageDialog(rootPane, saida);
                    findPforms();
                } catch (Exception ex) {
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayFormFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayFormFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayFormFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayFormFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayFormFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelPformButton;
    private javax.swing.JMenu deletePformMenu;
    private javax.swing.JTextField editIdPform;
    private javax.swing.JTextField editNamePform;
    private javax.swing.JDialog editPformDialog;
    private javax.swing.JMenu editPformMenu;
    private javax.swing.JLabel formLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JMenu newPformMenu;
    private javax.swing.JMenuBar pformMenuBar;
    private javax.swing.JScrollPane pformScrollPane;
    private javax.swing.JTable pformsTable;
    private javax.swing.JButton savePformButton;
    // End of variables declaration//GEN-END:variables
}
