/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sumptus.view;

import java.security.NoSuchAlgorithmException;
import java.lang.NullPointerException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import sumptus.dao.DataBase;
import sumptus.dao.UserDAO;
import sumptus.model.User;

/**
 *
 * @author jessicadagostini
 */
public class UserLoginFrame extends javax.swing.JFrame {

    private UserDAO userDAO;
    private User user;
    private UserOutlaysFrame outlay;

    /**
     * Creates new form UserLogin
     */
    public UserLoginFrame() {
        initComponents();
        initLogin();
    }
    
    public void initLogin(){
        loginPanel.setVisible(true);
        newUserPanel.setVisible(false);
        try {
            userDAO = new UserDAO(DataBase.connection());
            user = new User();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Não foi possível conectar ao banco de dados " + ex.getMessage());
        }
        ImageIcon icon = new ImageIcon("img/logo.png");
        labelTitle.setIcon(icon);
        labelTitle1.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        inputLogin = new javax.swing.JTextField();
        labelLogin = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        newUserButton = new javax.swing.JButton();
        labelTitle = new javax.swing.JLabel();
        inputPassword = new javax.swing.JPasswordField();
        newUserPanel = new javax.swing.JPanel();
        inputNewName = new javax.swing.JTextField();
        inputNewLogin = new javax.swing.JTextField();
        inputNewAdmin = new javax.swing.JRadioButton();
        labelLogin1 = new javax.swing.JLabel();
        labelPassword1 = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        createUserButton = new javax.swing.JButton();
        loginUserButton = new javax.swing.JButton();
        labelTitle1 = new javax.swing.JLabel();
        labelPassword2 = new javax.swing.JLabel();
        inputVerifyPassword = new javax.swing.JPasswordField();
        inputNewPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sumptus");
        setResizable(false);

        inputLogin.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        labelLogin.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        labelLogin.setText("Login");

        labelPassword.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        labelPassword.setText("Senha");

        loginButton.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        loginButton.setText("Entrar");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        newUserButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        newUserButton.setText("Criar Conta");
        newUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserButtonActionPerformed(evt);
            }
        });

        labelTitle.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N

        inputPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(loginPanelLayout.createSequentialGroup()
                            .addGap(235, 235, 235)
                            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelLogin)
                                .addComponent(labelPassword))
                            .addGap(89, 89, 89)
                            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(inputLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                                .addComponent(inputPassword)))
                        .addGroup(loginPanelLayout.createSequentialGroup()
                            .addGap(449, 449, 449)
                            .addComponent(newUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newUserButton)
                .addGap(64, 64, 64)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLogin)
                    .addComponent(inputLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addComponent(inputPassword)
                        .addGap(2, 2, 2))
                    .addComponent(labelPassword))
                .addGap(30, 30, 30)
                .addComponent(loginButton)
                .addGap(192, 192, 192))
        );

        inputNewName.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        inputNewLogin.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        inputNewAdmin.setText("Administrador");

        labelLogin1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        labelLogin1.setText("Login");

        labelPassword1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        labelPassword1.setText("Senha");

        labelNome.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        labelNome.setText("Nome");

        createUserButton.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        createUserButton.setText("Criar");
        createUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserButtonActionPerformed(evt);
            }
        });

        loginUserButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        loginUserButton.setText("Login");
        loginUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUserButtonActionPerformed(evt);
            }
        });

        labelTitle1.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N

        labelPassword2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        labelPassword2.setText("Repetir Senha");

        inputVerifyPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        inputVerifyPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputVerifyPasswordActionPerformed(evt);
            }
        });

        inputNewPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        inputNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNewPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newUserPanelLayout = new javax.swing.GroupLayout(newUserPanel);
        newUserPanel.setLayout(newUserPanelLayout);
        newUserPanelLayout.setHorizontalGroup(
            newUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newUserPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(442, 442, 442))
            .addGroup(newUserPanelLayout.createSequentialGroup()
                .addGroup(newUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newUserPanelLayout.createSequentialGroup()
                        .addGroup(newUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newUserPanelLayout.createSequentialGroup()
                                .addGap(263, 263, 263)
                                .addGroup(newUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelLogin1)
                                    .addComponent(labelPassword1)
                                    .addComponent(labelNome))
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newUserPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelPassword2)
                                .addGap(18, 18, 18)))
                        .addGroup(newUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputNewName, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newUserPanelLayout.createSequentialGroup()
                                .addComponent(inputNewAdmin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(createUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(inputNewLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                            .addComponent(inputVerifyPassword)
                            .addComponent(inputNewPassword, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(newUserPanelLayout.createSequentialGroup()
                        .addGap(388, 388, 388)
                        .addComponent(labelTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        newUserPanelLayout.setVerticalGroup(
            newUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newUserPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(labelTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginUserButton)
                .addGap(30, 30, 30)
                .addGroup(newUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelNome)
                    .addComponent(inputNewName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(newUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelLogin1)
                    .addComponent(inputNewLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(newUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelPassword1)
                    .addComponent(inputNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(newUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelPassword2)
                    .addComponent(inputVerifyPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(newUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newUserPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(createUserButton))
                    .addGroup(newUserPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(inputNewAdmin)))
                .addGap(121, 121, 121))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(newUserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(newUserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        try {
            user = userDAO.findByLogin(inputLogin.getText());
            if(inputPassword.getText().equals(user.getPassword())){
                JOptionPane.showMessageDialog(rootPane, "Login realizado com sucesso!");
                this.dispose();
                outlay = new UserOutlaysFrame(user);
                outlay.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Usuário ou senha incorreto.");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        } catch (NullPointerException ex){
            JOptionPane.showMessageDialog(rootPane, "Usuário ou senha incorreto.");
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void newUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserButtonActionPerformed
        loginPanel.setVisible(false);
        newUserPanel.setVisible(true);
    }//GEN-LAST:event_newUserButtonActionPerformed

    private void createUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserButtonActionPerformed
        if(inputNewLogin.getText().length() > 0 && inputNewPassword.getText().length() > 0){
            user.setName(inputNewName.getText());
            user.setLogin(inputNewLogin.getText().trim());
            user.setAdmin(inputNewAdmin.isSelected());
            try {
                if(inputNewPassword.getText().equals(inputVerifyPassword.getText())){
                    user.setPassword(inputNewPassword.getText().trim());
                }        
                String saida = userDAO.create(user);
                JOptionPane.showMessageDialog(rootPane, saida);
                newUserPanel.setVisible(false);
                loginPanel.setVisible(true);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Não foi possível criar seu usuário.");
            } catch (NullPointerException ex){
                JOptionPane.showMessageDialog(rootPane, "Não foi possível criar seu usuário.");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Não foi possível criar seu usuário.");
        }
    }//GEN-LAST:event_createUserButtonActionPerformed

    private void loginUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUserButtonActionPerformed
        loginPanel.setVisible(true);
        newUserPanel.setVisible(false);
    }//GEN-LAST:event_loginUserButtonActionPerformed

    private void inputVerifyPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputVerifyPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputVerifyPasswordActionPerformed

    private void inputNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNewPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNewPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserLoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createUserButton;
    private javax.swing.JTextField inputLogin;
    private javax.swing.JRadioButton inputNewAdmin;
    private javax.swing.JTextField inputNewLogin;
    private javax.swing.JTextField inputNewName;
    private javax.swing.JPasswordField inputNewPassword;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JPasswordField inputVerifyPassword;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelLogin1;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelPassword1;
    private javax.swing.JLabel labelPassword2;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelTitle1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JButton loginUserButton;
    private javax.swing.JButton newUserButton;
    private javax.swing.JPanel newUserPanel;
    // End of variables declaration//GEN-END:variables
}
